import datetime as dt
import streamlit as st
import pandas as pd

# Set page config
st.set_page_config(page_title="flight_operations", layout="wide")

# Title
st.title("flight_operations")

# Initialize Snowflake session
session = st.connection("snowflake").session()

@st.cache_data(ttl="23h50m")
def execute_query(query: str) -> str:
  return session.sql(query).collect_nowait().query_id

def query_1_1() -> str:
  sql_query = r"""
SELECT SUM(ON_GROUND) FROM FLIGHT_KPIS ;  """

  return sql_query

execute_query(query_1_1())

@st.fragment
def cell_1_1():
  with st.container(border=True):
    with st.container(horizontal=True, horizontal_alignment="distribute", vertical_alignment="center"):
      st.markdown("### Total On-Ground")
      if st.button(
        ":material/refresh:", type="tertiary", key=f"refresh_button_cell_1_1", help="Refresh total_on-ground data"
      ):
        execute_query.clear(query_1_1())

    try:
      with st.spinner("Executing query", show_time=True):
        df = session.create_async_job(
          execute_query(query_1_1())
        ).result("pandas")

      if any(df.columns.duplicated()):
        new_names = []
        name_indexes = {}
        for name in df.columns:
          name_index = name_indexes.get(name, 0) + 1
          name_indexes[name] = name_index
          new_names.append(f"{name}_{name_index}" if name_index > 1 else name)
        df.columns = new_names

      # Calculate metric for scorecard
      if len(df) > 0:
        value = df["SUM(ON_GROUND)"].iloc[0]
        st.metric(
          label="SUM(ON_GROUND)",
          value=f"{value:,.0f}"
        )
      else:
        st.warning("No data available")
    except Exception as e:
      st.error(f"Error: {str(e)}")

def query_1_2() -> str:
  sql_query = r"""
SELECT SUM(TOTAL_FLIGHTS) FROM FLIGHT_KPIS;  """

  return sql_query

execute_query(query_1_2())

@st.fragment
def cell_1_2():
  with st.container(border=True):
    with st.container(horizontal=True, horizontal_alignment="distribute", vertical_alignment="center"):
      st.markdown("### Total Flights")
      if st.button(
        ":material/refresh:", type="tertiary", key=f"refresh_button_cell_1_2", help="Refresh total_flights data"
      ):
        execute_query.clear(query_1_2())

    try:
      with st.spinner("Executing query", show_time=True):
        df = session.create_async_job(
          execute_query(query_1_2())
        ).result("pandas")

      if any(df.columns.duplicated()):
        new_names = []
        name_indexes = {}
        for name in df.columns:
          name_index = name_indexes.get(name, 0) + 1
          name_indexes[name] = name_index
          new_names.append(f"{name}_{name_index}" if name_index > 1 else name)
        df.columns = new_names

      # Calculate metric for scorecard
      if len(df) > 0:
        value = df["SUM(TOTAL_FLIGHTS)"].iloc[0]
        st.metric(
          label="SUM(TOTAL_FLIGHTS)",
          value=f"{value:,.0f}"
        )
      else:
        st.warning("No data available")
    except Exception as e:
      st.error(f"Error: {str(e)}")

# Row 1: 2 Cells
col1_1, col1_2 = st.columns(2)
with col1_1:
  cell_1_1()
with col1_2:
  cell_1_2()

def query_2_1() -> str:
  sql_query = r"""
SELECT ORIGIN_COUNTRY, 
    ON_GROUND 
    FROM FLIGHT_KPIS
    ORDER BY ON_GROUND DESC
    LIMIT 5    
;  """

  return sql_query

execute_query(query_2_1())

@st.fragment
def cell_2_1():
  with st.container(border=True):
    with st.container(horizontal=True, horizontal_alignment="distribute", vertical_alignment="center"):
      st.markdown("### Top 5 countries by On-Ground count")
      if st.button(
        ":material/refresh:", type="tertiary", key=f"refresh_button_cell_2_1", help="Refresh top_5_countries_by_on-ground_count data"
      ):
        execute_query.clear(query_2_1())

    try:
      with st.spinner("Executing query", show_time=True):
        df = session.create_async_job(
          execute_query(query_2_1())
        ).result("pandas")

      if any(df.columns.duplicated()):
        new_names = []
        name_indexes = {}
        for name in df.columns:
          name_index = name_indexes.get(name, 0) + 1
          name_indexes[name] = name_index
          new_names.append(f"{name}_{name_index}" if name_index > 1 else name)
        df.columns = new_names

      # Prepare data for bar chart
      if len(df) > 0:
        df = df.groupby(
          by="ORIGIN_COUNTRY",
          sort=False
        ).agg(
          col1=("ON_GROUND", "sum")
        ).rename(columns={
          "col1": "ON_GROUND (sum)"
        }).reset_index()

        df["/* Order Key (Generated by Snowflake) */"] = df.drop(columns="ORIGIN_COUNTRY").sum(axis=1)

        datetime_primary_column = None
        if pd.api.types.is_datetime64_dtype(df["ORIGIN_COUNTRY"]):
          datetime_primary_column = df["ORIGIN_COUNTRY"]
        elif df["ORIGIN_COUNTRY"].dtype == "object" and isinstance(df["ORIGIN_COUNTRY"].get(df["ORIGIN_COUNTRY"].first_valid_index()), dt.date):
          datetime_primary_column = pd.to_datetime(df["ORIGIN_COUNTRY"], errors="coerce")
        if datetime_primary_column is not None and (datetime_primary_column.max() - datetime_primary_column.min()).days > len(df) * 2:
          # Use string type for sparse date range
          df["ORIGIN_COUNTRY"] = df["ORIGIN_COUNTRY"].astype("string")

        st.bar_chart(
          df,
          x="ORIGIN_COUNTRY",
          y=[c for c in df.columns if c != "ORIGIN_COUNTRY" and c != "/* Order Key (Generated by Snowflake) */"],
          sort="-/* Order Key (Generated by Snowflake) */",
          use_container_width=True,
          height=400,
          horizontal=True,
          stack=False,
        )
      else:
        st.warning("No data available")
    except Exception as e:
      st.error(f"Error: {str(e)}")

def query_2_2() -> str:
  sql_query = r"""
SELECT TOTAL_FLIGHTS, ORIGIN_COUNTRY FROM FLIGHT_KPIS ORDER BY TOTAL_FLIGHTS DESC LIMIT 5;  """

  return sql_query

execute_query(query_2_2())

@st.fragment
def cell_2_2():
  with st.container(border=True):
    with st.container(horizontal=True, horizontal_alignment="distribute", vertical_alignment="center"):
      st.markdown("### Top 5 countries by Total Flights")
      if st.button(
        ":material/refresh:", type="tertiary", key=f"refresh_button_cell_2_2", help="Refresh top_5_countries_by_total_flights data"
      ):
        execute_query.clear(query_2_2())

    try:
      with st.spinner("Executing query", show_time=True):
        df = session.create_async_job(
          execute_query(query_2_2())
        ).result("pandas")

      if any(df.columns.duplicated()):
        new_names = []
        name_indexes = {}
        for name in df.columns:
          name_index = name_indexes.get(name, 0) + 1
          name_indexes[name] = name_index
          new_names.append(f"{name}_{name_index}" if name_index > 1 else name)
        df.columns = new_names

      # Prepare data for bar chart
      if len(df) > 0:
        df = df.groupby(
          by="ORIGIN_COUNTRY",
          sort=False
        ).agg(
          col1=("TOTAL_FLIGHTS", "sum")
        ).rename(columns={
          "col1": "TOTAL_FLIGHTS (sum)"
        }).reset_index()

        df["/* Order Key (Generated by Snowflake) */"] = df.drop(columns="ORIGIN_COUNTRY").sum(axis=1)

        datetime_primary_column = None
        if pd.api.types.is_datetime64_dtype(df["ORIGIN_COUNTRY"]):
          datetime_primary_column = df["ORIGIN_COUNTRY"]
        elif df["ORIGIN_COUNTRY"].dtype == "object" and isinstance(df["ORIGIN_COUNTRY"].get(df["ORIGIN_COUNTRY"].first_valid_index()), dt.date):
          datetime_primary_column = pd.to_datetime(df["ORIGIN_COUNTRY"], errors="coerce")
        if datetime_primary_column is not None and (datetime_primary_column.max() - datetime_primary_column.min()).days > len(df) * 2:
          # Use string type for sparse date range
          df["ORIGIN_COUNTRY"] = df["ORIGIN_COUNTRY"].astype("string")

        st.bar_chart(
          df,
          x="ORIGIN_COUNTRY",
          y=[c for c in df.columns if c != "ORIGIN_COUNTRY" and c != "/* Order Key (Generated by Snowflake) */"],
          sort="-/* Order Key (Generated by Snowflake) */",
          use_container_width=True,
          height=400,
          horizontal=True,
          stack=False,
        )
      else:
        st.warning("No data available")
    except Exception as e:
      st.error(f"Error: {str(e)}")

# Row 2: 2 Cells
col2_1, col2_2 = st.columns(2)
with col2_1:
  cell_2_1()
with col2_2:
  cell_2_2()


# Footer
st.markdown("---")
st.markdown(
  "*Dashboard loaded: {}*".format(dt.datetime.now().strftime("%Y-%m-%d %H:%M:%S"))
)
